### PR TITLE
Analyzer per project fix (and other small things)

### LINKED ISSUE #330: ensimeCompileOnly should accept parameters
instead of having its own configuration it would be very convenient to have a parser that accepts parameters to scalac.

e.g. `foo/ensimeCompileOnly -Xprint:typer /path/to/foo.scala` or `foo/ensimeCompileOnly -X`

### LINKED ISSUE #333: default server version should be friendly to 2.10
we should probably use `ensimeScalaVersion` when setting `ensimeServerVersion` and auto flip to `2.0.0-M1` for scala 2.10.

### LINKED ISSUE #339: Fix scalac-options/compiler-options
Sam, really sorry with all these questions, but what key am I to put the settings under:
With a ensime.sbt in project:

```
ensimeScalacOptions in ThisBuild:= Seq(
    "-feature",
    "-deprecation",
    "-Xlint",
    "-Ywarn-dead-code",
    "-Ywarn-numeric-widen",
    "-Xfuture",
    "-Ymacro-expand:discard"
)
```

I still get the default:

```
 :compiler-args ("-deprecation" "-unchecked" "-feature" "-language:postfixOps" "-language:implicitConversions" "-Xmax-classfile-name" "200" "-Xlint" "-Ywarn-dead-code" "-Ywarn-numeric-widen" "-Xfuture" "-Ywarn-unused-import" "-Ymacro-expand:discard")
```

And for all subprojects:
     
```
:scalac-options ("-deprecation" "-unchecked" "-feature" "-language:postfixOps" "-language:implicitConversions" "-Xmax-classfile-name" "200" "-feature" "-deprecation" "-Xlint" "-Ywarn-dead-code" "-Ywarn-numeric-widen" "-Xfuture" "-Ywarn-unused-import" "-Ymacro-expand:discard")
```

Removing in ThisBuild I get compiler-args fixed, but not scalac-options under the subprojects… I'm confused…

Sam Halliday @fommil 16:22

> scalac-options is ignored right now
> but will be used pretty soon
> (it's what Vishesh is working on)
> I think I'd have the same expectation as you in sbt-ensime so I think that's a bug
> can you raise one please?
> just copy / paste this discussion is fine
> 

Viktor Hedefalk @hedefalk 16:24
Sure!

Sam Halliday @fommil 16:24
oh, hold on, it's worse than I thought... you're still unable to change the :compiler-args
hmm, ok that should definitely be supported

### LINKED ISSUE #340: need .asc filter in the ensimeConfigProject

### LINKED ISSUE #343: test projects should depend on their compile phase
damn, causes https://github.com/ensime/ensime-server/issues/1805

### PR DESCRIPTION
**Pull request by fommil**
- close #343 
- close #333
- close #339
- close #340
- close #330

### CODE REVIEW

File: src/main/scala/EnsimePlugin.scala [hunk 1]
```diff
@@ -24,7 +24,7 @@ object EnsimeKeys {
     "Start up the ENSIME server and index your project."
   )
 
-  val ensimeServerVersion = settingKey[String](
+  val ensimeServerVersion = taskKey[String](
```
Comment (yyadavalli) [inline src/main/scala/EnsimePlugin.scala:27]: I think this should still be a setting, left to the user to decide.

Comment (fommil) [reply src/main/scala/EnsimePlugin.scala:27]: can't be... depends on other tasks :sob:

Comment (yyadavalli) [reply src/main/scala/EnsimePlugin.scala:27]: But if that is the case, the user cannot override it at all, they will have to use SNAPSHOT. I could be wrong if the definition order matters.

Comment (fommil) [reply src/main/scala/EnsimePlugin.scala:27]: setting is just a performance optimisation, user can still override (and uses exactly the same syntax). The difference is that it is always evaluated, instead of evaluated only once.

Comment (yyadavalli) [reply src/main/scala/EnsimePlugin.scala:27]: I know that, forgot that the user definition takes precedence. All good !!

**Comment by fommil** [comment]
ok, "this one small thing" turned into rather a lot of bug squishing :smile:
